### ISSUE TITLE
Cucumber steps with special characters like '.' getting truncated

### ISSUE THREAD

**Issue by gazal-k** [allure-framework/allure-cucumberjvm#14] opened 2015-06-24 19:37 UTC
I've a simple cucumber scenario like this:

Scenario: logging in with valid credentials
        Given login using username "abc@xyz.com" and password "password"
        Then response status should be 200

The XML in the allure-results folder looks like this:

``` xml
<test-cases>
        <test-case start="1435171984954" stop="1435171984954" status="passed">
            <name>Given login using username "abc@xyz.com" and password "password"</name>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="x"/>
                <label name="thread" value="x"/>
            </labels>
        </test-case>
...
</test-cases>
```

The final allure report truncates the test case name:

![screenshot from 2015-06-25 01 03 56](https://cloud.githubusercontent.com/assets/8210299/8339598/45a26e72-1ad6-11e5-81dc-e6213683827d.png)

Is there any configuration to escape special characters in the XML?
If someone can point me in the right direction, I would be glad to contribute.

**Comment by vania-pooh** [comment] 2015-06-25 07:42
@gazal-k I think this is an issue in adapter because it's invalid to have double quote inside XML tags (should be `&quot;`). But let's ask adapter developer. Also please tell us Allure version you're using.
@clicman any thoughts about it?

**Comment by clicman** [comment] 2015-06-25 07:50
No. It happened because of dot in titles. Additionally it is no problem to use double quotes inside tags for xml, it would be invalid only if appears in node attrbutes. Core problem was described in https://github.com/allure-framework/allure-core/issues/442
And this issue is duplicate of #10

**Comment by vania-pooh** [comment] 2015-06-25 07:55
@clicman agreed.

**Closed as completed** 2015-06-25 07:55 UTC
Labels: duplicate

**Comment by gazal-k** [comment] 2015-06-25 09:49
@clicman is a fix in progress? Any workarounds?

**Comment by clicman** [comment] 2015-06-25 10:02
@gazal-k as workaround you can remove dots from step names.
To get issue status ask it in https://github.com/allure-framework/allure-core/issues/408
And finally you can build your own report generator artifact. This PR soves problem: https://github.com/allure-framework/allure-core/pull/478 (but it not accepted to upstream). Anyway you can use it without any side effects.
@vania-pooh @baev guys, any additions?

**Comment by gazal-k** [comment] 2015-06-25 11:46
@clicman I thought the issue was with the dot character.

**Comment by clicman** [comment] 2015-06-25 11:49
@gazal-k Oh, sorry, you right. My typo. I was meand dots of course :)
