### ISSUE TITLE
1.6.3 - Incorrect Scenario Outlines behavior  

### ISSUE THREAD

**Issue by unickq** [allure-framework/allure-cucumberjvm#50] opened 2017-08-22 08:23 UTC
Hey there,

Cloned CucumberJvmExample repository and changed a bit ran following scenario:

```
@en
Feature: Test allure English

  Scenario: Test multiply
    Given first digit 5
    And second digit 5
    When I multiply it
    Then sum is 10

  Scenario Outline: Two digits multiply
    Given first digit <first>
    And second digit <second>
    When I multiply it
    Then sum is <sum>

    Examples: 
      | first  | second | sum   |
      | 6      | 6      | 11    |
      | 5      | 10     | 15    |
```

**Expected**: 3 scenarios in allure report: 1 **passed** _Test multiply_, 1 **passed** and 1 **failed** _Two digits multiply_
**Actual**: Only last step of scenario outline scenario is published

**mvn clean test**

> 3 Scenarios (1 failed, 2 passed)
> 12 Steps (1 failed, 11 passed)

Allure 2.3.4 shows: 2 passed scenarios:
1) Test multiply
2) Two digits multiply    | 5      | 10     | 15    |

![](https://image.prntscr.com/image/oYY9BjksSqmJtzCaqHUIFg.png)
![](https://image.prntscr.com/image/Mje83BoTS2SXUfzsfAtn1w.png)

**Comment by clicman** [comment] 2017-08-22 08:30
Hi! Actually, it is expected behaviour, because scenario outline is the same test case with different dataset.
But making it flaky is unexpected behavior. And somewhere I saw an issue on it.

**Comment by unickq** [comment] 2017-08-22 08:41
@clicman 
So is it impossible to publish scenario outline data as a separate test case?

I mean how we can see failed dataset as well?

**Comment by clicman** [comment] 2017-08-22 08:45
By design, it will be marked as flaky and you'll see which one failed in test history (retries)

**Comment by unickq** [comment] 2017-08-22 09:05
Ok, thanks.

Just wondered why the last failed data set item fails the whole test case and last successful marks it passed even if other are different :)

```
    Examples: 
      | first  | second | sum   |
      | 6      | 6      | 12    |
      | 5      | 10     | 11    |
```

![1](https://user-images.githubusercontent.com/6696821/29557541-1c7a162e-8732-11e7-8d51-9cdee1f31bf9.png)
![2](https://user-images.githubusercontent.com/6696821/29557540-1c790dd8-8732-11e7-80cc-d10232bc5a8c.png)

We can close this issue if that designed that way

**Comment by clicman** [comment] 2017-08-22 09:10
Sometimes hard to integrate cucumber logic into allure. This is one of these difficulties )

**Closed as completed by clicman** 2017-08-22 09:10 UTC

**Comment by mikesalvia** [comment] 2018-04-16 16:47
@clicman Maybe this can get re-opened, the Allure Cucumber Ruby adaptor is indeed able to take the parameters of the Scenario Outline and appends them to the Scenario Outline title.

**Comment by mikesalvia** [comment] 2018-04-16 16:48
<img width="683" alt="screen shot 2018-04-16 at 12 47 57 pm" src="https://user-images.githubusercontent.com/6209204/38823483-720ba894-4174-11e8-8c13-c6689256a214.png">
It looks like it should be being done here... However I am seeing them all grouped together.
